// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Price_Quotation_App.Data;

#nullable disable

namespace Price_Quotation_App.Migrations
{
    [DbContext(typeof(PriceQuotationContext))]
    partial class PriceQuotationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Price_Quotation_App.Models.PriceQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PriceQuotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 10m,
                            DiscountPercent = 10m,
                            Slug = "quote-1",
                            Subtotal = 100m,
                            Total = 90m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 37.50m,
                            DiscountPercent = 15m,
                            Slug = "quote-2",
                            Subtotal = 250m,
                            Total = 212.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
